"""Tour inventory for Falmouth Shore Excursion — sourced from Shore Excursions Group Falmouth port."""

TOURS: list[dict] = [
    {
        "slug": "dunns-river-falls-tour",
        "title": "Dunn's River Falls Tour",
        "seg_desc": "For guests wanting nothing more than to climb the falls, this focused tour takes you straight to Jamaica's most iconic waterfall.",
        "duration": "3 Hours 30 Minutes",
        "activity": "Moderate",
        "size": "Small",
        "category": "waterfall",
        "badge": "Best Waterfall Tour",
        "featured": True,
    },
    {
        "slug": "dunns-river-falls-and-area-highlights",
        "title": "Dunn's River Falls and Area Highlights",
        "seg_desc": "Escape large cruise ship tours on this exclusive small-group excursion to famous Dunn's River Falls and the highlights of Ocho Rios.",
        "duration": "5 Hours 30 Minutes",
        "activity": "Moderate",
        "size": "Small",
        "category": "waterfall",
        "badge": "Best for First-Time Visitors",
        "featured": True,
    },
    {
        "slug": "jamaican-countryside-sightseeing-with-lunch",
        "title": "Jamaican Countryside Sightseeing with Lunch",
        "seg_desc": "Travel through Fern Gully and Claremont, visit a coffee farm and farmers market, then enjoy Jamaican lunch at Scotchies Jerk Center.",
        "duration": "5 Hours 30 Minutes",
        "activity": "Moderate",
        "size": "Standard",
        "category": "countryside",
        "badge": "Best Cultural Tour",
        "featured": True,
    },
    {
        "slug": "private-driver-guide-full-day",
        "title": "Private Driver Guide Full Day",
        "seg_desc": "Get around Jamaica in spacious air-conditioned comfort with your personal driver/guide. Set your own itinerary for six hours.",
        "duration": "6 Hours",
        "activity": "Easy",
        "size": "Private",
        "category": "private",
        "badge": "Best Private Tour",
        "featured": True,
    },
    {
        "slug": "martha-brae-river-rafting",
        "title": "Martha Brae River Rafting",
        "seg_desc": "Drift along the tranquil Martha Brae River on a traditional bamboo raft guided by skilled raftsmen sharing river history and folklore.",
        "duration": "4 Hours",
        "activity": "Easy",
        "size": "Standard",
        "category": "martha",
        "badge": "Best River Experience",
        "featured": True,
    },
    {
        "slug": "blue-hole-adventure",
        "title": "Blue Hole Adventure",
        "seg_desc": "Spend the day in the beauty and tranquility of the Jamaican rainforest with a visit to the Blue Hole, an unspoiled gem in the hills of St. Mary.",
        "duration": "6 Hours",
        "activity": "Easy",
        "size": "Standard",
        "category": "bluehole",
        "badge": "Best Adventure Tour",
        "featured": True,
    },
    {
        "slug": "beach-escape-excursion",
        "title": "Beach Escape Excursion",
        "seg_desc": "Ready for a beach day in beautiful Jamaica? Your beach destination is packed with fun things to do near Falmouth.",
        "duration": "5 Hours 30 Minutes",
        "activity": "Easy",
        "size": "Standard",
        "category": "beach",
        "badge": "Best for Families",
        "featured": True,
    },
    {
        "slug": "river-tubing-adventure",
        "title": "River Tubing Adventure",
        "seg_desc": "For guests wanting to see Jamaica's countryside at a slower pace, this lazy river float is just the right tour.",
        "duration": "3 Hours 30 Minutes",
        "activity": "Moderate",
        "size": "Small",
        "category": "tubing",
        "badge": "Best Adventure Tour",
        "featured": False,
    },
    {
        "slug": "jamaica-highlights-tour",
        "title": "Jamaica Highlights Tour",
        "seg_desc": "Discover the secrets of Rose Hall Great House and Montego Bay's storied past during this illuminating city and heritage tour.",
        "duration": "5 Hours",
        "activity": "Moderate",
        "size": "Standard",
        "category": "highlights",
        "badge": "Best for Couples",
        "featured": False,
    },
    {
        "slug": "rum-and-culture-experience",
        "title": "Rum and Culture Experience",
        "seg_desc": "Witness the 260-year-old rum-making process at Hampden Estate distillery, followed by an exquisite tasting of Jamaica's finest rums.",
        "duration": "5 Hours 30 Minutes",
        "activity": "Moderate",
        "size": "Standard",
        "category": "rum",
        "badge": "Best Cultural Tour",
        "featured": False,
    },
]

TOUR_PAGES = [t["slug"] for t in TOURS]
FEATURED_TOURS = [t["slug"] for t in TOURS if t.get("featured")]

GUIDE_SLUGS = [
    "falmouth-port-guide",
    "one-day-in-falmouth-from-a-cruise-ship",
    "best-falmouth-shore-excursions",
    "dunns-river-falls-guide",
    "martha-brae-river-rafting-guide",
    "blue-hole-jamaica-guide",
    "is-falmouth-safe-for-cruise-passengers",
    "can-you-explore-falmouth-without-an-excursion",
    "best-beaches-near-falmouth-jamaica",
    "jamaican-rum-and-culture-guide",
]

SITEMAP_PAGES = [
    ("", "1.0", "weekly"),
    ("best-falmouth-shore-excursions", "0.9", "monthly"),
    ("best-beaches-near-falmouth-jamaica", "0.9", "monthly"),
    ("martha-brae-river-rafting-guide", "0.9", "monthly"),
    ("martha-brae-river-rafting", "0.9", "monthly"),
    ("falmouth-port-guide", "0.9", "monthly"),
    ("one-day-in-falmouth-from-a-cruise-ship", "0.8", "monthly"),
    ("falmouth-shore-excursions-faq", "0.8", "monthly"),
    ("dunns-river-falls-guide", "0.8", "monthly"),
    ("blue-hole-jamaica-guide", "0.8", "monthly"),
    ("is-falmouth-safe-for-cruise-passengers", "0.7", "monthly"),
    ("can-you-explore-falmouth-without-an-excursion", "0.7", "monthly"),
    ("jamaican-rum-and-culture-guide", "0.7", "monthly"),
    ("about", "0.5", "yearly"),
    ("contact", "0.5", "yearly"),
    ("privacy", "0.4", "yearly"),
    ("terms", "0.4", "yearly"),
    ("methodology", "0.4", "yearly"),
] + [(slug, "0.8", "monthly") for slug in TOUR_PAGES if slug != "martha-brae-river-rafting"]
